---
title: "Logistic Regression"
author: "Joshua Harasaki, Tiffany Chiang, Katie Huynh"
date: "3/13/2022"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(tidyr)
library(ggplot2)
```

## Loading Data

```{r}
data = read.csv('./data/processed/processed_data.csv')  # load data
head(data)  # print first 5 rows of data
```

```{r}
# create column telling us whether customer responded to any  
data$AcceptedCmp <- as.factor(ifelse(data$TotalAcceptedCmp > 0, 1, 0))
table(data$AcceptedCmp)
```

```{r}
qplot(AcceptedCmp, Total_Spending, data = data, geom = "boxplot")
```
```{r}
glm.fit = glm(AcceptedCmp ~ Education + Marital_Status + Income + Recency + NumWebVisitsMonth + 
                Total_Spending + Age + Children + TotalNumPurchases, data=data, family = binomial)
```

```{r}
# summarize the logisitic regression model
summary(glm.fit)
```
```{r}
prob.training = predict(glm.fit, type = "response")

round(prob.training, digits = 2)
```
```{r}
data = data %>% mutate(predAccept = as.factor(ifelse(prob.training <= 0.5, "No", "Yes")))
table(pred = data$predAccept, true = data$AcceptedCmp)
```














